#version 460
#extension GL_EXT_shader_16bit_storage                   : require
#extension GL_EXT_shader_8bit_storage                    : require
#extension GL_EXT_nonuniform_qualifier                   : require
#extension GL_EXT_shader_image_int64                     : require
#extension GL_EXT_shader_explicit_arithmetic_types_int64 : require
#extension GL_GOOGLE_include_directive                   : enable
#extension GL_ARB_shader_draw_parameters                 : require
#extension GL_KHR_shader_subgroup_arithmetic             : require
#extension GL_KHR_shader_subgroup_ballot                 : require
#extension GL_KHR_shader_subgroup_shuffle                : require
#extension GL_EXT_debug_printf                           : enable

layout(local_size_x = 8, local_size_y = 4, local_size_z = 1) in;

#include "../shader_includes/host_device_shared.h"
#include "../shader_includes/util/ui64_conv.glsl"
#include "../shader_includes/util/glsl_helpers.glsl"
#include "../shader_includes/types.glsl"
#include "../shader_includes/common_ubo.glsl"

// +------------------------------------------------------------------------------+
// |   Bound Resources                                                            |
// +------------------------------------------------------------------------------+
// layout(set = 0, binding = 0) buffer is contained within common_ubo.glsl
layout(set = 1, binding = 0) buffer SsboCounters { uint mCounters[4]; } uCounters;
layout(set = 2, binding = 0) buffer PatchLodPing { px_fill_data mElements[]; } uPatchLodPing; // initial target
//layout(set = 2, binding = 1) buffer PatchLodPong { px_fill_data mElements[]; } uPatchLodPong; // unused in this whole shader
layout(set = 2, binding = 2) buffer PatchLodCount { uvec4 mDispatchCounts[]; } uPatchLodCount; 

#include "../shader_includes/parametric_functions/shape_functions.glsl"

// +------------------------------------------------------------------------------+
// |   PushConstants                                                              |
// +------------------------------------------------------------------------------+

layout(push_constant) uniform PushConstants
{
	float4 mParameters;
    uint   mCurveIndex;
    uint   mObjectId;
}
pushConstants;

// ################## compute shader main ###################
void main()
{
	const uint   objectId          = pushConstants.mObjectId;
	const uint   curveIndex        = pushConstants.mCurveIndex;
	const uint   glyphId           = gl_WorkGroupID.x;
	const uvec2  datasetDimensions = uObjectData.mElements[objectId].mDetailEvalDims.zw;

	// in:
	const vec2 paramsFrom = pushConstants.mParameters.xz;
	const vec2 paramsTo   = pushConstants.mParameters.yw;

	const uvec2 evalDims    = clamp(uObjectData.mElements[objectId].mDetailEvalDims.xy, uvec2(1, 1), gl_WorkGroupSize.xy);
	const uvec3 translation = uvec3(gl_WorkGroupID.x, gl_WorkGroupID.y, 0);

	// out:
	const uint insertIdx = atomicAdd(uPatchLodCount.mDispatchCounts[0].x, 1); // start with the first, a.k.a. "firstPing"
	uPatchLodPing.mElements[insertIdx].mParams                = vec4(paramsFrom[0], paramsTo[0], paramsFrom[1], paramsTo[1]);
	uPatchLodPing.mElements[insertIdx].mObjectIdUserData      = uvec4(objectId, /* SH glyph translation : */ translation);
	uPatchLodPing.mElements[insertIdx].mScreenDistsHybridData = vec4(0.0, 0.0, intBitsToFloat(0), 1.0);
}
