#version 460
#extension GL_EXT_nonuniform_qualifier                   : require
#extension GL_EXT_shader_image_int64                     : require
#extension GL_EXT_shader_explicit_arithmetic_types_int64 : require
#extension GL_GOOGLE_include_directive                   : enable
#extension GL_EXT_debug_printf                           : enable

layout(local_size_x = 256, local_size_y = 1, local_size_z = 1) in;

#include "../shader_includes/host_device_shared.h"
#include "../shader_includes/util/ui64_conv.glsl"
#include "../shader_includes/types.glsl"
#include "../shader_includes/host_device_shared.h"
#include "../shader_includes/util/glsl_helpers.glsl"

// ###### BOUND RESOURCES #################################
#include "../shader_includes/common_ubo.glsl"
layout(set = 1, binding = 0) buffer SsboCounters { uint mCounters[4]; } uCounters;
layout(set = 2, binding = 0) buffer SeashellLodIndexMapping { uint mMappedIndex[]; } uSeashellLodIndexMapping;
layout(set = 2, binding = 1) buffer SeashellLodDrawParamsBuffer { PaddedVkDrawIndexedIndirectCommand mDrawParams[]; } uSeashellLodDrawParamsBuffer;
// -------------------------------------------------------

#define NICE_CLEAR_COLOR 0

// +------------------------------------------------------------------------------+
// |   PushConstants                                                              |
// +------------------------------------------------------------------------------+

layout(push_constant) uniform PushConstants
{
    int   mNumLods;
    float mQuality;
}
pushConstants;

// ################## compute shader main ###################
void main()
{
	if (gl_GlobalInvocationID.x >= SEASHELL_GRID_DIM * SEASHELL_GRID_DIM) {
		return;
	}

	int seashellIndex = int(gl_GlobalInvocationID.x);

    int x = (seashellIndex - 1) / 71;
    int y = (seashellIndex - 1) % 71;
    vec3 seashellPos = vec3(5.0 * (x - 36), 0.0, 5.0 * (y - 36));

	// ==== VIEW FRUSTUM CULLING   BEGIN ====
	const float radius = -10.0;
	for (int f = 0; f < 6; ++f) {
		if (classify_point(ubo.mFrustumPlanes[f], seashellPos) < radius)
			return;
	}
	// ==== VIEW FRUSTUM CULLING    END  ====

	vec4 posCS = ubo.mViewProjMatrix * vec4(seashellPos, 1.0);
	vec3 vpc = cs_to_viewport(posCS, ubo.mResolutionAndCulling.xy);

	const float quality = pushConstants.mQuality; // default is 4.0 (set from host side)
	// Move #quality-many pixels towards the center of the screen, then reproject into view space:
	vec3 vpc2 = vpc;
	vpc2.y += vpc.y < ubo.mResolutionAndCulling.y ? quality : -quality;
	vec3 vs2  = viewport_to_vs(vpc2, ubo.mResolutionAndCulling.xy, ubo.mInverseProjMatrix);
	// Compute the threshold in view space <= The chosen LOD mesh shall provide more detail than this.
	float thresholdVS = length(vs2 - (ubo.mViewMatrix * vec4(seashellPos, 1.0)).xyz);

	const int numBuckets = pushConstants.mNumLods; // number of actually loaded discrete 3D models
	int bucket = 0;
	for (; bucket < numBuckets; ++bucket) {
		if (uSeashellLodDrawParamsBuffer.mDrawParams[bucket]._padding2 < thresholdVS) {
			break;
		}
	}
	// If it overshot, it points at an invalid LOD => reset to LOD 0 to indicate it to the user:
	bucket = bucket < numBuckets ? bucket : 0;

#if STATS_ENABLED
	atomicAdd(uCounters.mCounters[3], 1);
#endif

//	int bucket = clamp(6 - int(dist / 30.0), 0, 6);
//	int bucket = 0;
	const uint insertIdx = atomicAdd(uSeashellLodDrawParamsBuffer.mDrawParams[bucket].instanceCount, 1);
	uSeashellLodIndexMapping.mMappedIndex[SEASHELL_LOD_IDS_STRIDE * bucket + insertIdx] = seashellIndex; // < The seashell index defines its position (see simple.vert)
}
